language: python

python:
  - "3.6"
  - "3.7"

dist: xenial

sudo: false

services:
  - docker

before_install:
  - git clone https://github.com/oceanprotocol/barge
  - cd barge
  - export KEEPER_VERSION=v0.10.3
  - export AQUARIUS_VERSION=v0.3.8
  - bash -x start_ocean.sh --no-brizo --no-pleuston --no-aquarius --local-spree-node 2>&1 > start_ocean.log &
  - cd ..

install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
  on:
    tags: true
    repo: oceanprotocol/events-handler-py
    python: 3.6

notifications:
  email: false
